input_select:
  clockface_selector:
    name: Clockface Selector
    options:
      - pacman
      - mario
    initial: pacman

automation:
  - alias: Change Clockface
    trigger:
      platform: state
      entity_id: input_select.clockface_selector
    action:
      service: esphome.clockwise_clock_set_clockface
      data:
        type: "{{ states('input_select.clockface_selector') }}"