esphome:
  name: clockwise_pacman
  friendly_name: Clockwise Pacman

  platformio_options:
    lib_deps:
      - Networking
      - WiFi
      - EEPROM
      - adafruit/Adafruit BusIO 
      - adafruit/Adafruit GFX Library  
      - https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA
    build_flags:
      - -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
      - -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WiFi/src
      - -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/EEPROM/src
    lib_ldf_mode: chain+      

external_components:
  - source: github://aschoelzhorn/clockwise-esphome@main
    #refresh: 1s  # just for debugging

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Clockwise Clock"
    password: !secret wifi_ap_password

time:
  - platform: sntp
    id: sntp_time

clockwise_pacman_ext:
  id: pacmanclk
  width: 64
  height: 64
  brightness: 180
  time_id: sntp_time
  driver: FM6126A
  clock_phase: false
  i2c_speed: 20M
  pins:
    r1: 2
    g1: 6
    b1: 10
    r2: 3
    g2: 7
    b2: 11
    a: 39
    b: 38
    c: 37
    d: 36
    e: 21
    lat: 33
    oe: 35
    clk: 34
